spring:
  zipkin:
    base-url: http://zipkin:9411/
    service:
      name: ${spring.application.name}
  main:
    allow-bean-definition-overriding: true

feign:
  url:
    auth: ${AUTH_SERVICE:https://auth.socshared.ml}
    fb: ${FB_SERVICE:localhost:8081}
    vk-adapter: http://vk-adapter
    tech-support: http://tech-support
    storage: ${STORAGE_SERVICE:localhost:8686}

