spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/db
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://zipkin:9411/
    service:
      name: ${spring.application.name}
  main:
    allow-bean-definition-overriding: true

facebook:
  redirect:
    uri: https://socshared.ml/connect/fb
  adapter:
    id: fb-adapter-prod

feign:
  url:
    auth: ${AUTH_SERVICE:localhost:9999}
    fb: ${FB_SERVICE:localhost:8081}
    vk-adapter: http://vk-adapter
    tech-support: localhost:8885
    storage: ${STORAGE_SERVICE:localhost:8686}