spring:
  datasource:
    url: jdbc:h2:mem:facebook_db?useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: https://zipkin.socshared.ml/
    service:
      name: ${spring.application.name}
  main:
    allow-bean-definition-overriding: true

feign:
  url:
    auth: ${AUTH_SERVICE:https://auth.socshared.ml}
    fb: ${FB_SERVICE:localhost:8081}
    vk-adapter: localhost:8082
    tech-support: localhost:8885
    storage: ${STORAGE_SERVICE:localhost:8686}

