spring:
  datasource:
    url: jdbc:h2:mem:facebook_db?useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: https://zipkin.socshared.ml/
    service:
      name: ${spring.application.name}
  main:
    allow-bean-definition-overriding: true

feign:
  url:
    auth: ${AUTH_SERVICE:localhost:9999}
    fb: ${FB_SERVICE:localhost:8081}
    vk: ${VK_SERVICE:http://vk-adapter}
    tech-support: ${TECH_SUPPORT_SERVICE:localhost:8885}
    storage: ${STORAGE_SERVICE:localhost:8686}
    bstat: ${STORAGE_SERVICE:localhost:8884}
    stat: ${STAT_SERVICE:http://stat-service:8888}
    text: ${TEXT_SERVICE:https://text.socshared.ml}
