spring:
  zipkin:
    base-url: http://zipkin:9411/
    service:
      name: ${spring.application.name}
  main:
    allow-bean-definition-overriding: true

feign:
  url:
    auth: ${AUTH_SERVICE:localhost:9999}
    fb: ${FB_SERVICE:localhost:8081}
    vk-adapter: https://vk.socshared.ml/
    storage: ${STORAGE_SERVICE:localhost:8686}

