spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/db
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://zipkin:9411/
    service:
      name: ${spring.application.name}
  main:
    allow-bean-definition-overriding: true

facebook:
  redirect:
    uri: https://socshared.ml/connect/fb
  adapter:
    id: fb-adapter-prod

feign:
  url:
    auth: ${AUTH_SERVICE:https://auth.socshared.ml}
    fb: ${FB_SERVICE:localhost:8081}
    vk: ${VK_SERVICE:http://vk-adapter}
    tech-support: ${TECH_SUPPORT_SERVICE:http://tech-support}
    storage: ${STORAGE_SERVICE:localhost:8686}
    stat: ${STAT_SERVICE:http://stat-service:8888}
