spring:
  datasource:
    url: jdbc:h2:mem:facebook_db?useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: https://zipkin.socshared.ml/
    service:
      name: ${spring.application.name}
  main:
    allow-bean-definition-overriding: true

feign:
  url:
    auth: ${AUTH_SERVICE:localhost:19999}
    fb: ${FB_SERVICE:localhost:8081}
    vk: ${VK_SERVICE:localhost:8082}
    tech-support: ${TECH_SUPPORT_SERVICE:localhost:8885}
    text: ${TEXT_SERVICE:http://text-analyzer:8886}
    storage: ${STORAGE_SERVICE:localhost:8686}
    bstat: ${BSTAT_SERVICE:localhost:8884}


